#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

import os

AUTHOR = u'chtangwin'

SITENAME = u'chtangwin'
SITESUBTITLE = u'Dive into Stats/FinMath'
# Change in publishconf.py and ignore the WARNING.  This is needed so you
# can inspect the site using a web-server at locahost.
SITEURL = 'https://chtangwin.github.io'

#PATH = 'content'

# Times and dates.
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'America/New_York'
DEFAULT_LANG = u'en'

# Set the article URL.
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

# Title menu options.
uri = 'http://chtangwin.github.io'
MENUITEMS = [('Blog', '%s/chtangwin' % uri),
             ('Archives', '%s/chtangwin/archives.html' % uri),
             ('About', '%s/homepage' % uri),
             ]
NEWEST_FIRST_ARCHIVES = True

# Feed generation is usually not desired when developing
#FEED_ALL_ATOM = None
#CATEGORY_FEED_ATOM = None
#TRANSLATION_FEED_ATOM = None
#AUTHOR_FEED_ATOM = None
#AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
         ('Python.org', 'http://python.org/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),
         ('You can modify those links in your config file', '#'),)

# Social widget
#SOCIAL = (('You can add links in your config file', '#'),
#          ('Another social link', '#'),)

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
RELATIVE_URLS = True

# STATIC_OUT_DIR requires pelican 3.3+.
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png']
CODE_DIR     = 'code'
NOTEBOOK_DIR = 'notebooks'

# Theme and plug-ins.
THEME = 'pelican-octopress-theme'
PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = ['summary', 'liquid_tags.img', 'liquid_tags.video',
           'liquid_tags.include_code', 'liquid_tags.notebook',
           'liquid_tags.literal']

DISPLAY_PAGES_ON_MENU = False
DISPLAY_CATEGORIES_ON_MENU = False

# The theme file should be updated so that the base header contains the line:
# {% if EXTRA_HEADER %}
# {{ EXTRA_HEADER }}
# {% endif %}

# This header file is automatically generated by the notebook plugin.
#if not os.path.exists('./_nb_header.html'):
#    print '@@TEST cwd = ', os.getcwd()
#    import warnings
#    warnings.warn("_nb_header.html not found.  "
#                  "Rerun make html to finalize build.")
#else:
#    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')

# RSS/Atom feeds
FEED_DOMAIN = 'http://chtangwin.github.io/'
FEED_ATOM = 'atom.xml'

# Search
SEARCH_BOX = True
